# Site settings
name: Less Or More
email: 1160522425@qq.com
author: chenxp38
url: none
resume_site: none
github: https://github.com/chenxp38/
baseurl: ""
description: Actually, less is more!
meta_description: Personal blog, use others frame, content written by myself
motto: none
banner: 就算很菜也要挣扎一下

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: chenxp38

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

